import { Platform, StyleSheet } from 'react-native';

import { colors } from './colors';

export const sharedStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  appShell: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  headerLogo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  logoBox: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#ffffff',
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoImage: {
    width: 38,
    height: 44,
  },
  brandSmall: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 1.4,
  },
  brand: {
    color: '#ffffff',
    fontSize: 26,
    fontWeight: '900',
  },
  headerPill: {
    backgroundColor: 'rgba(255,255,255,0.15)',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  headerPillText: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '800',
  },
  content: {
    flex: 1,
  },
  contentInner: {
    padding: 18,
    paddingBottom: 110,
  },
  hero: {
    backgroundColor: colors.primary,
    borderRadius: 20,
    padding: 22,
  },
  eyebrow: {
    color: colors.accent,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  heroTitle: {
    color: '#ffffff',
    fontSize: 30,
    fontWeight: '900',
    lineHeight: 36,
    marginTop: 14,
  },
  heroText: {
    color: '#d8e7df',
    fontSize: 15,
    lineHeight: 23,
    marginTop: 12,
  },
  heroFeatureRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 18,
  },
  heroFeature: {
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderColor: 'rgba(255,255,255,0.16)',
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    paddingHorizontal: 10,
    paddingVertical: 12,
  },
  heroFeatureValue: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: '900',
    textAlign: 'center',
  },
  heroFeatureLabel: {
    color: 'rgba(255,255,255,0.68)',
    fontSize: 11,
    fontWeight: '800',
    marginTop: 2,
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  heroCityFeature: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderColor: 'rgba(255,255,255,0.16)',
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  heroCityValue: {
    color: '#ffffff',
    fontSize: 22,
    fontWeight: '900',
    textAlign: 'center',
    width: '100%',
  },
  quickActions: {
    flexDirection: 'row',
    marginTop: 14,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 14,
    flex: 1,
    justifyContent: 'center',
    marginTop: 14,
    minHeight: 50,
    paddingHorizontal: 14,
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '900',
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    marginLeft: 10,
    marginTop: 14,
    minHeight: 50,
    paddingHorizontal: 14,
  },
  secondaryButtonText: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: '900',
  },
  disabledButton: {
    backgroundColor: '#aebbb4',
  },
  simulatorSubmitButton: {
    flex: 0,
    width: '100%',
  },
  statsRow: {
    flexDirection: 'row',
    marginHorizontal: -4,
    marginTop: 14,
  },
  statCard: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    marginHorizontal: 4,
    padding: 12,
  },
  statValue: {
    color: colors.primary,
    fontSize: 22,
    fontWeight: '900',
  },
  statLabel: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '800',
    marginTop: 4,
  },
  sectionHeader: {
    marginBottom: 12,
    marginTop: 26,
  },
  sectionTitle: {
    color: colors.text,
    fontSize: 28,
    fontWeight: '900',
  },
  sectionSubtitle: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 21,
    marginTop: 6,
  },
  card: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 16,
    borderWidth: 1,
    marginBottom: 12,
    padding: 16,
  },
  compactCard: {
    padding: 12,
  },
  cardTop: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  cardMain: {
    flex: 1,
    paddingRight: 10,
  },
  freshness: {
    color: colors.green,
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 8,
  },
  badgeRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  countryCode: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 1.2,
    marginRight: 8,
  },
  badge: {
    borderRadius: 999,
    marginBottom: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  badgeText: {
    fontSize: 11,
    fontWeight: '900',
  },
  transitBadge: {
    alignSelf: 'flex-start',
    backgroundColor: colors.orangeSoft,
    borderRadius: 999,
    marginTop: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  transitBadgeText: {
    color: colors.orange,
    fontSize: 11,
    fontWeight: '900',
  },
  cardTitle: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '900',
    lineHeight: 26,
    marginTop: 6,
  },
  cardSubtitle: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 20,
    marginTop: 5,
  },
  priceBox: {
    alignItems: 'flex-end',
    backgroundColor: colors.primarySoft,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 8,
    marginRight: 10,
  },
  priceLabel: {
    color: colors.muted,
    fontSize: 10,
    fontWeight: '800',
  },
  price: {
    color: colors.primary,
    fontSize: 16,
    fontWeight: '900',
    marginTop: 3,
  },
  detailList: {
    marginTop: 12,
  },
  detail: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 20,
    marginTop: 4,
  },
  cardButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 12,
    marginTop: 14,
    paddingVertical: 12,
  },
  cardButtonText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '900',
  },
  input: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 14,
    borderWidth: 1,
    color: colors.text,
    fontSize: 15,
    minHeight: 50,
    marginBottom: 12,
    paddingHorizontal: 14,
  },
  simulatorGrid: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
  },
  simulatorColumn: {
    flex: 1,
    minWidth: 0,
  },
  label: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 1,
    marginBottom: 8,
    marginTop: 12,
    textTransform: 'uppercase',
  },
  stepper: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  stepperButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 10,
    height: 38,
    justifyContent: 'center',
    width: 42,
  },
  stepperButtonText: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '900',
    lineHeight: 20,
  },
  stepperValue: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '900',
    paddingHorizontal: 10,
    textAlign: 'center',
  },
  optionGroup: {
    marginTop: 8,
  },
  optionRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginHorizontal: -4,
  },
  option: {
    alignItems: 'center',
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 12,
    borderWidth: 1,
    margin: 4,
    minWidth: 92,
    paddingHorizontal: 16,
    paddingVertical: 11,
  },
  optionTwoColumn: {
    flexBasis: '47%',
    flexGrow: 1,
    minWidth: 0,
  },
  optionFullWidth: {
    flexBasis: '100%',
    flexGrow: 1,
    minWidth: 0,
  },
  optionActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  optionText: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '800',
    textAlign: 'center',
    width: '100%',
  },
  optionTextActive: {
    color: '#ffffff',
  },
  warningText: {
    backgroundColor: colors.orangeSoft,
    borderRadius: 12,
    color: colors.orange,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 19,
    marginTop: 8,
    padding: 12,
  },
  simStateCard: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 18,
    padding: 24,
    alignItems: 'center',
    minHeight: 220,
    justifyContent: 'center',
  },
  simStateKicker: {
    color: colors.primary,
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginTop: 16,
  },
  simStateTitle: {
    color: colors.text,
    fontSize: 22,
    fontWeight: '900',
    lineHeight: 28,
    marginTop: 8,
    textAlign: 'center',
  },
  simStateText: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 22,
    marginTop: 10,
    textAlign: 'center',
  },
  simStateHint: {
    backgroundColor: colors.primarySoft,
    borderRadius: 12,
    marginTop: 14,
    padding: 12,
    width: '100%',
  },
  simStateHintText: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 20,
    textAlign: 'center',
  },
  resultCard: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 18,
    padding: 16,
  },
  resultKicker: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  resultTitle: {
    color: colors.text,
    fontSize: 24,
    fontWeight: '900',
    lineHeight: 30,
    marginTop: 8,
  },
  resultText: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 22,
    marginTop: 8,
  },
  dayCard: {
    backgroundColor: colors.background,
    borderRadius: 14,
    marginTop: 12,
    padding: 13,
  },
  dayTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '900',
  },
  dayTip: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: '800',
    lineHeight: 20,
    marginTop: 8,
  },
  officialNote: {
    backgroundColor: colors.primarySoft,
    borderRadius: 12,
    color: colors.primary,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 18,
    marginTop: 14,
    padding: 12,
  },
  stateBox: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    padding: 24,
  },
  compactStateBox: {
    backgroundColor: colors.dangerSoft,
    borderRadius: 16,
    flex: 0,
    marginTop: 14,
  },
  errorTitle: {
    color: colors.danger,
    fontSize: 18,
    fontWeight: '900',
    marginBottom: 8,
  },
  stateText: {
    color: colors.muted,
    fontSize: 15,
    lineHeight: 22,
    marginTop: 12,
    textAlign: 'center',
  },
  stateHint: {
    color: colors.muted,
    fontSize: 12,
    marginTop: 8,
    textAlign: 'center',
  },
  pillScroll: {
    marginBottom: 10,
  },
  pillScrollContent: {
    gap: 8,
    paddingRight: 4,
  },
  pill: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  pillActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  pillText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '800',
  },
  pillTextActive: {
    color: '#ffffff',
  },
  tabBar: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 22,
    borderWidth: 1,
    bottom: Platform.OS === 'ios' ? 36 : 18,
    flexDirection: 'row',
    left: 18,
    padding: 6,
    position: 'absolute',
    right: 18,
  },
  tabButton: {
    alignItems: 'center',
    borderRadius: 16,
    flex: 1,
    minWidth: 0,
    paddingHorizontal: 3,
    paddingVertical: 10,
  },
  tabButtonActive: {
    backgroundColor: colors.primary,
  },
  tabText: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '900',
    textAlign: 'center',
    width: '100%',
  },
  tabTextActive: {
    color: '#ffffff',
  },
  retryButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 14,
    marginTop: 16,
    paddingHorizontal: 28,
    paddingVertical: 12,
  },
  retryButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '900',
  },
  privacyLink: {
    alignItems: 'center',
    marginTop: 24,
    marginBottom: 8,
  },
  privacyLinkText: {
    color: colors.muted,
    fontSize: 12,
    textDecorationLine: 'underline',
  },
});
